// src/components/Ruler.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Calibration from './Calibration.svelte';

  const UNITS = ['cm', 'inches', 'mm'] as const;
  type Unit = typeof UNITS[number];

  interface GuideLine {
    id: string;
    type: 'horizontal' | 'vertical';
    position: number; // in pixels from origin
  }

  interface CalibrationData {
    method: 'auto' | 'device' | 'diagonal' | 'card' | 'manual' | null;
    dpi: number;
    confidence: number;
    deviceName: string | null;
    diagonal: number | null;
    cardAligned: boolean;
  }

  // State
  let currentUnit: Unit = 'cm';
  let isDarkMode = false;
  let showCrosshair = false;
  let showGuides = true;
  let guides: GuideLine[] = [];
  let guideToggle = 'horizontal'; // 'horizontal' | 'vertical'
  let crosshairPos = { x: 0, y: 0 };
  let viewportSize = { width: 0, height: 0 };
  let dpr = 1;
  let calibration: CalibrationData = {
    method: null,
    dpi: 96,
    confidence: 0,
    deviceName: null,
    diagonal: null,
    cardAligned: false
  };

  // DOM elements
  let rulerTop: HTMLElement;
  let rulerBottom: HTMLElement;
  let rulerLeft: HTMLElement;
  let rulerRight: HTMLElement;
  let canvas: HTMLCanvasElement;
  let ctx: CanvasRenderingContext2D;
  let crosshairEl: HTMLElement;
  let coordsEl: HTMLElement;
  let unitBtn: HTMLButtonElement;
  let darkBtn: HTMLButtonElement;
  let crosshairBtn: HTMLButtonElement;
  let guidesBtn: HTMLButtonElement;
  let fullscreenBtn: HTMLButtonElement;
  let guideToggleBtn: HTMLButtonElement;

  function getStored<T>(key: string, fallback: T): T {
    try {
      const item = localStorage.getItem(key);
      return item ? JSON.parse(item) : fallback;
    } catch {
      return fallback;
    }
  }

  function setStored(key: string, value: unknown) {
    localStorage.setItem(key, JSON.stringify(value));
  }

  function loadSettings() {
    currentUnit = getStored('ruler-unit', 'cm') as Unit;
    isDarkMode = getStored('ruler-dark', window.matchMedia('(prefers-color-scheme: dark)').matches);
    showCrosshair = getStored('ruler-crosshair', false);
    showGuides = getStored('ruler-guides', true);
    guides = getStored('ruler-guide-lines', []);
    guideToggle = getStored('ruler-guide-toggle', 'horizontal');
    applyTheme();
    updateUnitButton();
    updateButtons();
  }

  function applyTheme() {
    document.documentElement.classList.toggle('dark', isDarkMode);
    darkBtn.setAttribute('aria-pressed', String(isDarkMode));
  }

  function updateUnitButton() {
    unitBtn.textContent = `Unit: ${currentUnit.toUpperCase()}`;
    unitBtn.setAttribute('aria-label', `Current unit: ${currentUnit}, press U to cycle`);
    // Announce to screen readers
    announceToScreenReader(`Unit changed to ${currentUnit}`);
  }

  function announceToScreenReader(message: string) {
    const announcer = document.getElementById('sr-announcer');
    if (announcer) {
      announcer.textContent = message;
    }
  }

  function updateButtons() {
    crosshairBtn.setAttribute('aria-pressed', String(showCrosshair));
    guidesBtn.setAttribute('aria-pressed', String(showGuides));
    guideToggleBtn.textContent = `Guide: ${guideToggle.charAt(0).toUpperCase() + guideToggle.slice(1)}`;
    guideToggleBtn.setAttribute('aria-label', `Guide orientation: ${guideToggle}, click to toggle`);
  }

  function saveSettings() {
    setStored('ruler-unit', currentUnit);
    setStored('ruler-dark', isDarkMode);
    setStored('ruler-crosshair', showCrosshair);
    setStored('ruler-guides', showGuides);
    setStored('ruler-guide-lines', guides);
    setStored('ruler-guide-toggle', guideToggle);
  }

  function cycleUnit() {
    const idx = UNITS.indexOf(currentUnit);
    currentUnit = UNITS[(idx + 1) % UNITS.length];
    updateUnitButton();
    saveSettings();
    renderRulers();
  }

  function toggleDark() {
    isDarkMode = !isDarkMode;
    applyTheme();
    saveSettings();
    renderRulers();
    announceToScreenReader(`Dark mode ${isDarkMode ? 'enabled' : 'disabled'}`);
  }

  function toggleCrosshair() {
    showCrosshair = !showCrosshair;
    crosshairBtn.setAttribute('aria-pressed', String(showCrosshair));
    crosshairEl.style.display = showCrosshair ? 'block' : 'none';
    coordsEl.style.display = showCrosshair ? 'block' : 'none';
    saveSettings();
    announceToScreenReader(`Crosshair ${showCrosshair ? 'enabled' : 'disabled'}`);
  }

  function toggleGuides() {
    showGuides = !showGuides;
    guidesBtn.setAttribute('aria-pressed', String(showGuides));
    renderGuides();
    saveSettings();
    announceToScreenReader(`Guide lines ${showGuides ? 'enabled' : 'disabled'}`);
  }

  function toggleGuideOrientation() {
    guideToggle = guideToggle === 'horizontal' ? 'vertical' : 'horizontal';
    guideToggleBtn.textContent = `Guide: ${guideToggle.charAt(0).toUpperCase() + guideToggle.slice(1)}`;
    saveSettings();
  }

  function toggleFullscreen() {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => {});
    } else {
      document.exitFullscreen().catch(() => {});
    }
  }

  function getUnitInfo(unit: Unit) {
    switch (unit) {
      case 'mm':
        return { major: 10, minor: 1, label: 'mm', majorLabel: 'cm' };
      case 'cm':
        return { major: 10, minor: 1, label: 'mm', majorLabel: 'cm' };
      case 'inches':
        return { major: 1, minor: 1/16, label: 'in', majorLabel: 'in' };
    }
  }

  function pxPerUnit(unit: Unit): number {
    // Use calibrated DPI or fallback to 96
    const cssInch = calibration.dpi || 96;
    switch (unit) {
      case 'mm':
        return cssInch / 25.4 * dpr;
      case 'cm':
        return cssInch / 2.54 * dpr;
      case 'inches':
        return cssInch * dpr;
    }
  }

  function formatValue(value: number, unit: Unit): string {
    if (unit === 'inches') {
      // Show as fraction for inches
      const whole = Math.floor(value);
      const fraction = value - whole;
      const sixteenths = Math.round(fraction * 16);
      if (sixteenths === 0) return `${whole}"`;
      if (whole === 0) return `${sixteenths}/16"`;
      return `${whole} ${sixteenths}/16"`;
    }
    return `${value.toFixed(unit === 'mm' ? 0 : 1)}${unit}`;
  }

  function renderRulers() {
    if (!ctx || !canvas) return;

    const { width, height } = viewportSize;
    const unitInfo = getUnitInfo(currentUnit);
    const pxPerMajor = pxPerUnit(currentUnit) * unitInfo.major;
    const pxPerMinor = pxPerUnit(currentUnit) * unitInfo.minor;

    // Clear canvas
    ctx.clearRect(0, 0, width * dpr, height * dpr);

    // Set up canvas for high DPI
    ctx.save();
    ctx.scale(dpr, dpr);

    const isDark = isDarkMode;
    const axisColor = isDark ? '#666' : '#ccc';
    const textColor = isDark ? '#ddd' : '#333';
    const majorColor = isDark ? '#888' : '#999';
    const minorColor = isDark ? '#555' : '#ddd';

    // Top ruler
    ctx.fillStyle = isDark ? '#1a1a1a' : '#f5f5f5';
    ctx.fillRect(0, 0, width, 40);

    ctx.strokeStyle = axisColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, 40);
    ctx.lineTo(width, 40);
    ctx.stroke();

    // Top ruler marks
    const maxMajorTop = Math.floor(width / pxPerMajor);
    for (let i = 0; i <= maxMajorTop; i++) {
      const x = i * pxPerMajor;
      if (x > width) break;

      // Major tick
      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(x, 30);
      ctx.lineTo(x, 40);
      ctx.stroke();

      // Label
      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'bottom';
      ctx.fillText(formatValue(i * unitInfo.major, currentUnit), x, 28);

      // Minor ticks
      if (i < maxMajorTop) {
        const minorCount = unitInfo.major / unitInfo.minor;
        for (let m = 1; m < minorCount; m++) {
          const mx = x + m * pxPerMinor;
          if (mx > width) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(mx, 34);
          ctx.lineTo(mx, 40);
          ctx.stroke();
        }
      }
    }

    // Bottom ruler
    ctx.fillStyle = isDark ? '#1a1a1a' : '#f5f5f5';
    ctx.fillRect(0, height - 40, width, 40);

    ctx.strokeStyle = axisColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, height - 40);
    ctx.lineTo(width, height - 40);
    ctx.stroke();

    const maxMajorBottom = Math.floor(width / pxPerMajor);
    for (let i = 0; i <= maxMajorBottom; i++) {
      const x = i * pxPerMajor;
      if (x > width) break;

      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(x, height - 40);
      ctx.lineTo(x, height - 30);
      ctx.stroke();

      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'top';
      ctx.fillText(formatValue(i * unitInfo.major, currentUnit), x, height - 28);

      if (i < maxMajorBottom) {
        const minorCount = unitInfo.major / unitInfo.minor;
        for (let m = 1; m < minorCount; m++) {
          const mx = x + m * pxPerMinor;
          if (mx > width) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(mx, height - 36);
          ctx.lineTo(mx, height - 40);
          ctx.stroke();
        }
      }
    }

    // Left ruler
    ctx.fillStyle = isDark ? '#1a1a1a' : '#f5f5f5';
    ctx.fillRect(0, 0, 40, height);

    ctx.strokeStyle = axisColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, 0);
    ctx.lineTo(40, height);
    ctx.stroke();

    const maxMajorLeft = Math.floor(height / pxPerMajor);
    for (let i = 0; i <= maxMajorLeft; i++) {
      const y = i * pxPerMajor;
      if (y > height) break;

      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(30, y);
      ctx.lineTo(40, y);
      ctx.stroke();

      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'right';
      ctx.textBaseline = 'middle';
      ctx.fillText(formatValue(i * unitInfo.major, currentUnit), 28, y);

      if (i < maxMajorLeft) {
        const minorCount = unitInfo.major / unitInfo.minor;
        for (let m = 1; m < minorCount; m++) {
          const my = y + m * pxPerMinor;
          if (my > height) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(34, my);
          ctx.lineTo(40, my);
          ctx.stroke();
        }
      }
    }

    // Right ruler
    ctx.fillStyle = isDark ? '#1a1a1a' : '#f5f5f5';
    ctx.fillRect(width - 40, 0, 40, height);

    ctx.strokeStyle = axisColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(width - 40, 0);
    ctx.lineTo(width - 40, height);
    ctx.stroke();

    const maxMajorRight = Math.floor(height / pxPerMajor);
    for (let i = 0; i <= maxMajorRight; i++) {
      const y = i * pxPerMajor;
      if (y > height) break;

      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(width - 40, y);
      ctx.lineTo(width - 30, y);
      ctx.stroke();

      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'middle';
      ctx.fillText(formatValue(i * unitInfo.major, currentUnit), width - 28, y);

      if (i < maxMajorRight) {
        const minorCount = unitInfo.major / unitInfo.minor;
        for (let m = 1; m < minorCount; m++) {
          const my = y + m * pxPerMinor;
          if (my > height) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(width - 36, my);
          ctx.lineTo(width - 40, my);
          ctx.stroke();
        }
      }
    }

    ctx.restore();
    renderGuides();
  }

  function renderGuides() {
    if (!ctx || !canvas || !showGuides) return;

    const { width, height } = viewportSize;
    const isDark = isDarkMode;

    ctx.save();
    ctx.scale(dpr, dpr);

    guides.forEach(guide => {
      if (guide.type === 'horizontal') {
        // Horizontal guide line
        ctx.strokeStyle = isDark ? '#0af' : '#06f';
        ctx.lineWidth = 1;
        ctx.setLineDash([4, 4]);
        ctx.beginPath();
        ctx.moveTo(40, guide.position);
        ctx.lineTo(width - 40, guide.position);
        ctx.stroke();
        ctx.setLineDash([]);

        // Label
        const value = guide.position / pxPerUnit(currentUnit);
        ctx.fillStyle = isDark ? '#0af' : '#06f';
        ctx.font = 'bold 12px system-ui, sans-serif';
        ctx.textAlign = 'left';
        ctx.textBaseline = 'bottom';
        ctx.fillText(formatValue(value, currentUnit), 44, guide.position - 2);
      } else {
        // Vertical guide line
        ctx.strokeStyle = isDark ? '#0af' : '#06f';
        ctx.lineWidth = 1;
        ctx.setLineDash([4, 4]);
        ctx.beginPath();
        ctx.moveTo(guide.position, 40);
        ctx.lineTo(guide.position, height - 40);
        ctx.stroke();
        ctx.setLineDash([]);

        // Label
        const value = guide.position / pxPerUnit(currentUnit);
        ctx.fillStyle = isDark ? '#0af' : '#06f';
        ctx.font = 'bold 12px system-ui, sans-serif';
        ctx.textAlign = 'center';
        ctx.textBaseline = 'top';
        ctx.fillText(formatValue(value, currentUnit), guide.position, 44);
      }
    });

    ctx.restore();
  }

  function handlePointerMove(e: PointerEvent) {
    const rect = canvas.getBoundingClientRect();
    const x = (e.clientX - rect.left) * dpr;
    const y = (e.clientY - rect.top) * dpr;

    crosshairPos.x = x / dpr;
    crosshairPos.y = y / dpr;

    if (showCrosshair) {
      updateCrosshair();
    }
  }

  function updateCrosshair() {
    const { width, height } = viewportSize;
    const x = crosshairPos.x;
    const y = crosshairPos.y;

    // Crosshair lines
    crosshairEl.style.left = `${x}px`;
    crosshairEl.style.top = `${y}px`;

    // Coordinates display
    const unitInfo = getUnitInfo(currentUnit);
    const pxPerMajor = pxPerUnit(currentUnit);
    const coordX = x / pxPerMajor;
    const coordY = y / pxPerMajor;

    coordsEl.textContent = `X: ${formatValue(coordX, currentUnit)}  Y: ${formatValue(coordY, currentUnit)}`;
    coordsEl.style.left = `${Math.min(x + 16, width - 160)}px`;
    coordsEl.style.top = `${Math.min(y - 30, height - 60)}px`;
  }

  function handleClick(e: PointerEvent) {
    if (!showGuides) return;

    const rect = canvas.getBoundingClientRect();
    const x = (e.clientX - rect.left) * dpr;
    const y = (e.clientY - rect.top) * dpr;

    // Don't add guide if clicking on ruler areas
    if (x < 40 || x > viewportSize.width - 40 || y < 40 || y > viewportSize.height - 40) {
      return;
    }

    const guide: GuideLine = {
      id: crypto.randomUUID(),
      type: guideToggle,
      position: guideToggle === 'horizontal' ? y / dpr : x / dpr,
    };

    guides.push(guide);
    saveSettings();
    renderGuides();
  }

  function handleKeyDown(e: KeyboardEvent) {
    // Ignore if typing in input
    if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;

    switch (e.key.toLowerCase()) {
      case 'u':
        e.preventDefault();
        cycleUnit();
        break;
      case 'd':
        e.preventDefault();
        toggleDark();
        break;
      case 'c':
        e.preventDefault();
        toggleCrosshair();
        break;
      case 'g':
        e.preventDefault();
        toggleGuides();
        break;
      case 'f':
        e.preventDefault();
        toggleFullscreen();
        break;
      case 'k':
        e.preventDefault();
        // Open calibration modal
        const calibrationEvent = new CustomEvent('open-calibration');
        window.dispatchEvent(calibrationEvent);
        break;
    }
  }

  function handleResize() {
    viewportSize.width = window.innerWidth;
    viewportSize.height = window.innerHeight;
    dpr = window.devicePixelRatio || 1;

    canvas.width = viewportSize.width * dpr;
    canvas.height = viewportSize.height * dpr;
    canvas.style.width = `${viewportSize.width}px`;
    canvas.style.height = `${viewportSize.height}px`;

    renderRulers();

    if (showCrosshair) {
      updateCrosshair();
    }
  }

  function removeGuide(id: string) {
    guides = guides.filter(g => g.id !== id);
    saveSettings();
    renderGuides();
  }

  function clearAllGuides() {
    if (guides.length === 0) return;
    guides = [];
    saveSettings();
    renderGuides();
  }

  onMount(() => {
    // Initialize DOM references
    rulerTop = document.getElementById('ruler-top')!;
    rulerBottom = document.getElementById('ruler-bottom')!;
    rulerLeft = document.getElementById('ruler-left')!;
    rulerRight = document.getElementById('ruler-right')!;
    canvas = document.getElementById('ruler-canvas') as HTMLCanvasElement;
    ctx = canvas.getContext('2d')!;
    crosshairEl = document.getElementById('crosshair')!;
    coordsEl = document.getElementById('coords')!;
    unitBtn = document.getElementById('unit-btn') as HTMLButtonElement;
    darkBtn = document.getElementById('dark-btn') as HTMLButtonElement;
    crosshairBtn = document.getElementById('crosshair-btn') as HTMLButtonElement;
    guidesBtn = document.getElementById('guides-btn') as HTMLButtonElement;
    fullscreenBtn = document.getElementById('fullscreen-btn') as HTMLButtonElement;
    guideToggleBtn = document.getElementById('guide-toggle-btn') as HTMLButtonElement;

    loadSettings();
    handleResize();

    // Listen for calibration changes
    window.addEventListener('calibration-changed', ((e: CustomEvent<CalibrationData>) => {
      calibration = e.detail;
      renderRulers();
    }) as EventListener);

    // Event listeners
    window.addEventListener('resize', handleResize);
    window.addEventListener('pointermove', handlePointerMove);
    canvas.addEventListener('click', handleClick);
    window.addEventListener('keydown', handleKeyDown);

    unitBtn.addEventListener('click', cycleUnit);
    darkBtn.addEventListener('click', toggleDark);
    crosshairBtn.addEventListener('click', toggleCrosshair);
    guidesBtn.addEventListener('click', toggleGuides);
    fullscreenBtn.addEventListener('click', toggleFullscreen);
    guideToggleBtn.addEventListener('click', toggleGuideOrientation);

    // Touch support for crosshair
    canvas.addEventListener('touchstart', (e) => {
      if (e.touches.length === 1) {
        handlePointerMove(e.touches[0] as unknown as PointerEvent);
      }
    }, { passive: true });

    canvas.addEventListener('touchmove', (e) => {
      if (e.touches.length === 1) {
        handlePointerMove(e.touches[0] as unknown as PointerEvent);
      }
    }, { passive: true });

    // Context menu for guide removal
    canvas.addEventListener('contextmenu', (e) => {
      e.preventDefault();
      const rect = canvas.getBoundingClientRect();
      const x = (e.clientX - rect.left) * dpr;
      const y = (e.clientY - rect.top) * dpr;

      // Find guide near click
      const threshold = 20 / dpr;
      const idx = guides.findIndex(g => {
        if (g.type === 'horizontal') {
          return Math.abs(g.position - y / dpr) < threshold;
        } else {
          return Math.abs(g.position - x / dpr) < threshold;
        }
      });

      if (idx !== -1) {
        removeGuide(guides[idx].id);
      }
    });

    // Initial render
    renderRulers();
  });
</script>

<div id="ruler-app" class="ruler-app">
  <canvas id="ruler-canvas" class="ruler-canvas" aria-label="Ruler canvas"></canvas>

  <header class="app-header">
    <div class="brand-lockup">
      <span class="brand-mark" aria-hidden="true">R</span>
      <div>
        <strong>Real Ruler</strong>
        <span>Measure at actual size</span>
      </div>
    </div>
    <div class="header-status" aria-label="Ruler status">
      <span class="status-dot"></span>
      <span>Screen calibrated</span>
    </div>
  </header>

  <div id="crosshair" class="crosshair" aria-hidden="true">
    <div class="crosshair-h"></div>
    <div class="crosshair-v"></div>
  </div>

  <div id="coords" class="coords" aria-live="polite" aria-atomic="true"></div>

  <div class="controls" role="toolbar" aria-label="Ruler controls">
    <button id="unit-btn" class="control-btn" aria-label="Cycle units (U)"></button>
    <button id="dark-btn" class="control-btn" aria-label="Toggle dark mode (D)"></button>
    <button id="crosshair-btn" class="control-btn" aria-label="Toggle crosshair (C)"></button>
    <button id="guides-btn" class="control-btn" aria-label="Toggle guide lines (G)"></button>
    <button id="guide-toggle-btn" class="control-btn" aria-label="Toggle guide orientation"></button>
    <button id="fullscreen-btn" class="control-btn" aria-label="Toggle fullscreen (F)"></button>
    <button id="clear-guides-btn" class="control-btn" aria-label="Clear all guides" onclick={clearAllGuides}>Clear Guides</button>
  </div>

  <!-- Screen reader announcer -->
  <div id="sr-announcer" aria-live="polite" aria-atomic="true" class="sr-only"></div>

  <div class="shortcuts-help" aria-hidden="true">
    <kbd>U</kbd> Unit &nbsp;
    <kbd>D</kbd> Dark &nbsp;
    <kbd>C</kbd> Crosshair &nbsp;
    <kbd>G</kbd> Guides &nbsp;
    <kbd>F</kbd> Fullscreen &nbsp;
    <kbd>K</kbd> Calibrate &nbsp;
    <kbd>Click</kbd> Add guide &nbsp;
    <kbd>Right-click</kbd> Remove guide
  </div>
</div>

<Calibration />

<style>
  .ruler-app {
    position: fixed;
    inset: 0;
    overflow: hidden;
    background: #f4f7fb;
    color: #152238;
    font-family: 'Inter', 'Segoe UI', sans-serif;
    touch-action: none;
    -webkit-user-select: none;
    user-select: none;
  }

  :global(.dark) .ruler-app {
    background: #0e1726;
    color: #f4f7fb;
  }

  .app-header {
    position: fixed;
    inset: 0 0 auto;
    z-index: 15;
    display: flex;
    align-items: center;
    justify-content: space-between;
    min-height: 64px;
    padding: 10px 20px;
    pointer-events: none;
    background: linear-gradient(180deg, rgba(244, 247, 251, 0.96), rgba(244, 247, 251, 0));
  }

  :global(.dark) .app-header {
    background: linear-gradient(180deg, rgba(14, 23, 38, 0.96), rgba(14, 23, 38, 0));
  }

  .brand-lockup,
  .header-status {
    display: flex;
    align-items: center;
  }

  .brand-lockup {
    gap: 10px;
  }

  .brand-lockup > div {
    display: grid;
    gap: 2px;
  }

  .brand-lockup strong {
    color: #152238;
    font-size: 14px;
    letter-spacing: 0.01em;
  }

  .brand-lockup span:not(.brand-mark),
  .header-status {
    color: #68758a;
    font-size: 11px;
  }

  :global(.dark) .brand-lockup strong {
    color: #f4f7fb;
  }

  :global(.dark) .brand-lockup span:not(.brand-mark),
  :global(.dark) .header-status {
    color: #a9b6c8;
  }

  .brand-mark {
    display: grid;
    width: 32px;
    height: 32px;
    place-items: center;
    border: 1px solid rgba(38, 112, 255, 0.22);
    border-radius: 10px;
    background: #e9f1ff;
    color: #1463e8;
    font-size: 16px;
    font-weight: 800;
  }

  .header-status {
    gap: 7px;
    padding: 7px 10px;
    border: 1px solid rgba(106, 125, 151, 0.2);
    border-radius: 999px;
    background: rgba(255, 255, 255, 0.58);
    backdrop-filter: blur(12px);
  }

  :global(.dark) .header-status {
    background: rgba(22, 37, 59, 0.7);
  }

  .status-dot {
    width: 7px;
    height: 7px;
    border-radius: 50%;
    background: #16a568;
    box-shadow: 0 0 0 3px rgba(22, 165, 104, 0.13);
  }

  .ruler-canvas {
    position: absolute;
    inset: 0;
    display: block;
  }

  .crosshair {
    position: absolute;
    pointer-events: none;
    display: none;
    z-index: 10;
  }

  .crosshair-h,
  .crosshair-v {
    position: absolute;
    background: var(--accent, #06f);
    opacity: 0.6;
  }

  .crosshair-h {
    width: 100vw;
    height: 1px;
    top: 50%;
    left: 0;
    transform: translateY(-50%);
  }

  .crosshair-v {
    width: 1px;
    height: 100vh;
    left: 50%;
    top: 0;
    transform: translateX(-50%);
  }

  .coords {
    position: absolute;
    pointer-events: none;
    padding: 4px 8px;
    background: var(--bg-primary, #fff);
    border: 1px solid var(--border, #ccc);
    border-radius: 4px;
    font: 12px monospace;
    white-space: nowrap;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    z-index: 11;
    display: none;
  }

  .controls {
    position: fixed;
    top: 16px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
    gap: 8px;
    padding: 7px;
    background: rgba(255, 255, 255, 0.78);
    border: 1px solid rgba(106, 125, 151, 0.2);
    border-radius: 16px;
    box-shadow: 0 14px 35px rgba(30, 52, 82, 0.12);
    backdrop-filter: blur(18px);
    z-index: 20;
    flex-wrap: wrap;
    justify-content: center;
  }

  :global(.dark) .controls {
    background: rgba(20, 34, 54, 0.82);
    border-color: rgba(169, 182, 200, 0.2);
    box-shadow: 0 14px 35px rgba(0, 0, 0, 0.28);
  }

  .control-btn {
    padding: 9px 12px;
    border: 1px solid transparent;
    border-radius: 10px;
    background: transparent;
    color: #53647b;
    font: 600 12px 'Inter', 'Segoe UI', sans-serif;
    cursor: pointer;
    transition: background 0.15s ease, color 0.15s ease, border-color 0.15s ease;
    min-width: 44px;
    min-height: 44px;
  }

  .control-btn:hover {
    background: #edf3fc;
    border-color: #d8e4f5;
    color: #155dcc;
  }

  .control-btn:focus-visible {
    outline: 2px solid var(--accent, #06f);
    outline-offset: 2px;
  }

  .control-btn[aria-pressed="true"] {
    background: #1769e8;
    color: white;
    border-color: #1769e8;
  }

  :global(.dark) .control-btn {
    color: #b4c1d2;
  }

  :global(.dark) .control-btn:hover {
    background: #223a5d;
    border-color: #31547f;
    color: #e6efff;
  }

  .shortcuts-help {
    position: fixed;
    top: 82px;
    left: 50%;
    transform: translateX(-50%);
    padding: 8px 16px;
    background: rgba(255, 255, 255, 0.76);
    border: 1px solid rgba(106, 125, 151, 0.16);
    border-radius: 999px;
    font: 11px 'Inter', 'Segoe UI', sans-serif;
    color: #718096;
    white-space: nowrap;
    box-shadow: 0 2px 12px rgba(0,0,0,0.08);
    z-index: 15;
    opacity: 0.78;
  }

  .shortcuts-help kbd {
    padding: 2px 6px;
    background: var(--bg-secondary, #f0f0f0);
    border: 1px solid var(--border, #ccc);
    border-radius: 4px;
    font-family: monospace;
    font-size: 10px;
  }

  :global(.dark) .shortcuts-help kbd {
    background: #333;
    border-color: #555;
    color: #ddd;
  }

  @media (max-width: 480px) {
    .controls {
      bottom: 8px;
      top: auto;
      width: calc(100% - 16px);
      padding: 6px 8px;
      gap: 4px;
      border-radius: 18px;
    }

    .control-btn {
      padding: 6px 10px;
      font-size: 12px;
    }

    .shortcuts-help {
      top: 76px;
      font-size: 10px;
      padding: 6px 12px;
      max-width: calc(100% - 32px);
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .app-header {
      padding: 8px 12px;
    }

    .header-status {
      padding: 6px 8px;
    }

    .header-status span:last-child {
      display: none;
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .control-btn,
    .crosshair-h,
    .crosshair-v {
      transition: none;
    }
  }

  .sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
  }
</style>

// src/components/Ruler.tsx
import { useEffect, useRef, useState, useCallback } from 'react';
import CalibrationModal, { type CalibrationData } from './CalibrationModal';

const UNITS = ['cm', 'inches', 'mm'] as const;
type Unit = (typeof UNITS)[number];

interface GuideLine {
  id: string;
  type: 'horizontal' | 'vertical';
  position: number;
}

function getStored<T>(key: string, fallback: T): T {
  try {
    const item = localStorage.getItem(key);
    return item ? (JSON.parse(item) as T) : fallback;
  } catch {
    return fallback;
  }
}
function setStored(key: string, value: unknown) {
  localStorage.setItem(key, JSON.stringify(value));
}

function formatValue(value: number, unit: Unit): string {
  if (unit === 'inches') {
    const whole = Math.floor(value);
    const fraction = value - whole;
    const sixteenths = Math.round(fraction * 16);
    if (sixteenths === 0) return `${whole}"`;
    if (whole === 0) return `${sixteenths}/16"`;
    return `${whole} ${sixteenths}/16"`;
  }
  return `${value.toFixed(unit === 'mm' ? 0 : 1)}${unit}`;
}

function getUnitInfo(unit: Unit) {
  switch (unit) {
    case 'mm':
      return { major: 10, minor: 1 };
    case 'cm':
      return { major: 10, minor: 1 };
    case 'inches':
      return { major: 1, minor: 1 / 16 };
  }
}

function pxPerUnit(unit: Unit, dpi: number, dpr: number): number {
  switch (unit) {
    case 'mm':
      return (dpi / 25.4) * dpr;
    case 'cm':
      return (dpi / 2.54) * dpr;
    case 'inches':
      return dpi * dpr;
  }
}

export default function Ruler() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const crosshairRef = useRef<HTMLDivElement>(null);
  const coordsRef = useRef<HTMLDivElement>(null);

  const [unit, setUnit] = useState<Unit>(() => getStored('ruler-unit', 'cm'));
  const [dark, setDark] = useState<boolean>(() =>
    getStored('ruler-dark', typeof window !== 'undefined' ? window.matchMedia('(prefers-color-scheme: dark)').matches : false)
  );
  const [crosshair, setCrosshair] = useState<boolean>(() => getStored('ruler-crosshair', false));
  const [showGuides, setShowGuides] = useState<boolean>(() => getStored('ruler-guides', true));
  const [guides, setGuides] = useState<GuideLine[]>(() => getStored('ruler-guide-lines', []));
  const [guideToggle, setGuideToggle] = useState<'horizontal' | 'vertical'>(() =>
    getStored('ruler-guide-toggle', 'horizontal')
  );
  const [calibration, setCalibration] = useState<CalibrationData>({
    method: null,
    dpi: 96,
    confidence: 0,
    deviceName: null,
    diagonal: null,
    cardAligned: false,
  });
  const [showCalibration, setShowCalibration] = useState(false);
  const [viewport, setViewport] = useState({ width: 0, height: 0 });
  const [dpr, setDpr] = useState(1);
  const crosshairPos = useRef({ x: 0, y: 0 });

  const stateRef = useRef({ unit, dark, crosshair, showGuides, guides, guideToggle, calibration, dpr, viewport });
  stateRef.current = { unit, dark, crosshair, showGuides, guides, guideToggle, calibration, dpr, viewport };

  const announce = useCallback((msg: string) => {
    const el = document.getElementById('sr-announcer');
    if (el) el.textContent = msg;
  }, []);

  const renderRulers = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const s = stateRef.current;
    const { width, height } = s.viewport;
    const { dpr } = s;
    const info = getUnitInfo(s.unit);
    const pxMajor = pxPerUnit(s.unit, s.calibration.dpi, dpr);
    const pxMinor = pxPerUnit(s.unit, s.calibration.dpi, dpr) * info.minor;

    ctx.clearRect(0, 0, width * dpr, height * dpr);
    ctx.save();
    ctx.scale(dpr, dpr);

    const isDark = s.dark;
    const axisColor = isDark ? '#666' : '#ccc';
    const textColor = isDark ? '#ddd' : '#333';
    const majorColor = isDark ? '#888' : '#999';
    const minorColor = isDark ? '#555' : '#ddd';
    const bg = isDark ? '#1a1a1a' : '#f5f5f5';

    // --- Top ruler ---
    ctx.fillStyle = bg;
    ctx.fillRect(0, 0, width, 40);
    ctx.strokeStyle = axisColor;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, 40);
    ctx.lineTo(width, 40);
    ctx.stroke();
    const maxTop = Math.floor(width / pxMajor);
    for (let i = 0; i <= maxTop; i++) {
      const x = i * pxMajor;
      if (x > width) break;
      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(x, 30);
      ctx.lineTo(x, 40);
      ctx.stroke();
      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'bottom';
      ctx.fillText(formatValue(i * info.major, s.unit), x, 28);
      if (i < maxTop) {
        for (let m = 1; m < info.major / info.minor; m++) {
          const mx = x + m * pxMinor;
          if (mx > width) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(mx, 34);
          ctx.lineTo(mx, 40);
          ctx.stroke();
        }
      }
    }

    // --- Bottom ruler ---
    ctx.fillStyle = bg;
    ctx.fillRect(0, height - 40, width, 40);
    ctx.strokeStyle = axisColor;
    ctx.beginPath();
    ctx.moveTo(0, height - 40);
    ctx.lineTo(width, height - 40);
    ctx.stroke();
    const maxBottom = Math.floor(width / pxMajor);
    for (let i = 0; i <= maxBottom; i++) {
      const x = i * pxMajor;
      if (x > width) break;
      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(x, height - 40);
      ctx.lineTo(x, height - 30);
      ctx.stroke();
      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'top';
      ctx.fillText(formatValue(i * info.major, s.unit), x, height - 28);
      if (i < maxBottom) {
        for (let m = 1; m < info.major / info.minor; m++) {
          const mx = x + m * pxMinor;
          if (mx > width) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(mx, height - 36);
          ctx.lineTo(mx, height - 40);
          ctx.stroke();
        }
      }
    }

    // --- Left ruler ---
    ctx.fillStyle = bg;
    ctx.fillRect(0, 0, 40, height);
    ctx.strokeStyle = axisColor;
    ctx.beginPath();
    ctx.moveTo(40, 0);
    ctx.lineTo(40, height);
    ctx.stroke();
    const maxLeft = Math.floor(height / pxMajor);
    for (let i = 0; i <= maxLeft; i++) {
      const y = i * pxMajor;
      if (y > height) break;
      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(30, y);
      ctx.lineTo(40, y);
      ctx.stroke();
      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'right';
      ctx.textBaseline = 'middle';
      ctx.fillText(formatValue(i * info.major, s.unit), 28, y);
      if (i < maxLeft) {
        for (let m = 1; m < info.major / info.minor; m++) {
          const my = y + m * pxMinor;
          if (my > height) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(34, my);
          ctx.lineTo(40, my);
          ctx.stroke();
        }
      }
    }

    // --- Right ruler ---
    ctx.fillStyle = bg;
    ctx.fillRect(width - 40, 0, 40, height);
    ctx.strokeStyle = axisColor;
    ctx.beginPath();
    ctx.moveTo(width - 40, 0);
    ctx.lineTo(width - 40, height);
    ctx.stroke();
    const maxRight = Math.floor(height / pxMajor);
    for (let i = 0; i <= maxRight; i++) {
      const y = i * pxMajor;
      if (y > height) break;
      ctx.strokeStyle = majorColor;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(width - 40, y);
      ctx.lineTo(width - 30, y);
      ctx.stroke();
      ctx.fillStyle = textColor;
      ctx.font = '11px system-ui, sans-serif';
      ctx.textAlign = 'left';
      ctx.textBaseline = 'middle';
      ctx.fillText(formatValue(i * info.major, s.unit), width - 28, y);
      if (i < maxRight) {
        for (let m = 1; m < info.major / info.minor; m++) {
          const my = y + m * pxMinor;
          if (my > height) break;
          ctx.strokeStyle = minorColor;
          ctx.lineWidth = 1;
          ctx.beginPath();
          ctx.moveTo(width - 36, my);
          ctx.lineTo(width - 40, my);
          ctx.stroke();
        }
      }
    }

    ctx.restore();

    // Guides
    if (s.showGuides) {
      ctx.save();
      ctx.scale(dpr, dpr);
      s.guides.forEach((g) => {
        ctx.strokeStyle = isDark ? '#0af' : '#06f';
        ctx.lineWidth = 1;
        ctx.setLineDash([4, 4]);
        ctx.beginPath();
        if (g.type === 'horizontal') {
          ctx.moveTo(40, g.position);
          ctx.lineTo(width - 40, g.position);
        } else {
          ctx.moveTo(g.position, 40);
          ctx.lineTo(g.position, height - 40);
        }
        ctx.stroke();
        ctx.setLineDash([]);
        const value = g.position / pxPerUnit(s.unit, s.calibration.dpi, dpr);
        ctx.fillStyle = isDark ? '#0af' : '#06f';
        ctx.font = 'bold 12px system-ui, sans-serif';
        if (g.type === 'horizontal') {
          ctx.textAlign = 'left';
          ctx.textBaseline = 'bottom';
          ctx.fillText(formatValue(value, s.unit), 44, g.position - 2);
        } else {
          ctx.textAlign = 'center';
          ctx.textBaseline = 'top';
          ctx.fillText(formatValue(value, s.unit), g.position, 44);
        }
      });
      ctx.restore();
    }
  }, []);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const handleResize = () => {
      const w = Math.max(1, Math.floor(canvas.clientWidth));
      const h = Math.max(1, Math.floor(canvas.clientHeight));
      const d = window.devicePixelRatio || 1;
      canvas.width = w * d;
      canvas.height = h * d;
      setViewport({ width: w, height: h });
      setDpr(d);
    };

    handleResize();
    window.addEventListener('resize', handleResize);
    const ro = new ResizeObserver(handleResize);
    ro.observe(canvas);
    return () => {
      window.removeEventListener('resize', handleResize);
      ro.disconnect();
    };
  }, []);

  useEffect(() => {
    renderRulers();
  }, [renderRulers, unit, dark, crosshair, showGuides, guides, guideToggle, calibration, viewport, dpr]);

  // Persist settings
  useEffect(() => {
    setStored('ruler-unit', unit);
    setStored('ruler-dark', dark);
    setStored('ruler-crosshair', crosshair);
    setStored('ruler-guides', showGuides);
    setStored('ruler-guide-lines', guides);
    setStored('ruler-guide-toggle', guideToggle);
  }, [unit, dark, crosshair, showGuides, guides, guideToggle]);

  // Theme
  useEffect(() => {
    document.documentElement.classList.toggle('dark', dark);
  }, [dark]);

  // Crosshair DOM element sync
  useEffect(() => {
    const x = crosshairPos.current.x;
    const y = crosshairPos.current.y;
    if (crosshairRef.current) {
      crosshairRef.current.style.display = crosshair ? 'block' : 'none';
      crosshairRef.current.style.left = `${x}px`;
      crosshairRef.current.style.top = `${y}px`;
    }
    if (coordsRef.current) {
      coordsRef.current.style.display = crosshair ? 'block' : 'none';
    }
  }, [crosshair]);

  const handlePointerMove = useCallback(
    (e: PointerEvent) => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const rect = canvas.getBoundingClientRect();
      const s = stateRef.current;
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      crosshairPos.current = { x, y };
      if (s.crosshair) {
        if (crosshairRef.current) {
          crosshairRef.current.style.left = `${x}px`;
          crosshairRef.current.style.top = `${y}px`;
        }
        if (coordsRef.current) {
          const cx = x / pxPerUnit(s.unit, s.calibration.dpi, s.dpr);
          const cy = y / pxPerUnit(s.unit, s.calibration.dpi, s.dpr);
          coordsRef.current.textContent = `X: ${formatValue(cx, s.unit)}  Y: ${formatValue(cy, s.unit)}`;
          coordsRef.current.style.left = `${Math.min(x + 16, s.viewport.width - 160)}px`;
          coordsRef.current.style.top = `${Math.min(y - 30, s.viewport.height - 60)}px`;
        }
      }
    },
    []
  );

  const handleCanvasClick = useCallback(
    (e: React.MouseEvent) => {
      const s = stateRef.current;
      if (!s.showGuides) return;
      const canvas = canvasRef.current;
      if (!canvas) return;
      const rect = canvas.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      if (x < 40 || x > s.viewport.width - 40 || y < 40 || y > s.viewport.height - 40) return;
      const guide: GuideLine = {
        id: crypto.randomUUID(),
        type: s.guideToggle,
        position: s.guideToggle === 'horizontal' ? y : x,
      };
      setGuides((g) => [...g, guide]);
    },
    []
  );

  const handleContextMenu = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault();
      const canvas = canvasRef.current;
      if (!canvas) return;
      const rect = canvas.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      const threshold = 20;
      setGuides((prev) => {
        const idx = prev.findIndex((g) =>
          g.type === 'horizontal' ? Math.abs(g.position - y) < threshold : Math.abs(g.position - x) < threshold
        );
        if (idx === -1) return prev;
        return prev.filter((_, i) => i !== idx);
      });
    },
    []
  );

  const cycleUnit = useCallback(() => {
    setUnit((u) => {
      const idx = UNITS.indexOf(u);
      return UNITS[(idx + 1) % UNITS.length];
    });
    announce(`Unit changed to ${unit}`);
  }, [announce, unit]);

  const toggleDark = useCallback(() => {
    setDark((d) => !d);
    announce(`Dark mode ${!dark ? 'enabled' : 'disabled'}`);
  }, [announce, dark]);

  const toggleCrosshair = useCallback(() => {
    setCrosshair((c) => !c);
    announce(`Crosshair ${!crosshair ? 'enabled' : 'disabled'}`);
  }, [announce, crosshair]);

  const toggleGuides = useCallback(() => {
    setShowGuides((g) => !g);
    announce(`Guide lines ${!showGuides ? 'enabled' : 'disabled'}`);
  }, [announce, showGuides]);

  const toggleFullscreen = useCallback(() => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => {});
    } else {
      document.exitFullscreen().catch(() => {});
    }
  }, []);

  const clearAllGuides = useCallback(() => {
    if (guides.length === 0) {
      announce('There are no guide lines to clear');
      return;
    }
    setGuides([]);
    announce('All guide lines cleared');
  }, [announce, guides.length]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      switch (e.key.toLowerCase()) {
        case 'u':
          e.preventDefault();
          cycleUnit();
          break;
        case 'd':
          e.preventDefault();
          toggleDark();
          break;
        case 'c':
          e.preventDefault();
          toggleCrosshair();
          break;
        case 'g':
          e.preventDefault();
          toggleGuides();
          break;
        case 'f':
          e.preventDefault();
          toggleFullscreen();
          break;
        case 'k':
          e.preventDefault();
          setShowCalibration(true);
          break;
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [cycleUnit, toggleDark, toggleCrosshair, toggleGuides, toggleFullscreen]);

  useEffect(() => {
    window.addEventListener('pointermove', handlePointerMove);
    return () => window.removeEventListener('pointermove', handlePointerMove);
  }, [handlePointerMove]);

  const handleCalibrationChange = useCallback(
    (data: CalibrationData) => {
      setCalibration(data);
      localStorage.setItem('ruler-calibration', JSON.stringify(data));
    },
    []
  );

  useEffect(() => {
    const saved = getStored<CalibrationData | null>('ruler-calibration', null);
    if (saved) setCalibration(saved);
  }, []);

  const statusText = calibration.method
    ? `${calibration.dpi} PPI · Calibrated`
    : '96 PPI · Estimated';

  return (
    <div id="ruler-app" className={'ruler-app' + (dark ? ' dark-app' : '')}>
      <canvas
        ref={canvasRef}
        className="ruler-canvas"
        aria-label="Ruler canvas"
        onClick={handleCanvasClick}
        onContextMenu={handleContextMenu}
      />

      <header className="app-header">
        <div className="brand-lockup">
          <span className="brand-mark" aria-hidden="true">
            <svg viewBox="0 0 24 24">
              <path d="M5 5v14M5 7h8a3 3 0 0 1 0 6H5M13 13l5 6" />
            </svg>
          </span>
          <div>
            <strong>Real Ruler</strong>
            <span>Precision workspace</span>
          </div>
        </div>

        <div className="controls" role="toolbar" aria-label="Ruler controls">
          <button
            className="control-btn text-control unit-control"
            aria-label="Cycle units (U)"
            title="Change measurement unit"
            onClick={cycleUnit}
          >
            Unit: {unit.toUpperCase()}
          </button>
          <button
            className="control-btn icon-btn"
            aria-label="Toggle dark mode (D)"
            title="Toggle dark mode"
            aria-pressed={dark}
            onClick={toggleDark}
          >
            <svg className="theme-icon icon-sun" viewBox="0 0 24 24" aria-hidden="true">
              <circle cx="12" cy="12" r="4" />
              <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41" />
            </svg>
            <svg className="theme-icon icon-moon" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.7 6.7 0 0 0 21 12.8Z" />
            </svg>
          </button>
          <button
            className="control-btn icon-btn"
            aria-label="Toggle crosshair (C)"
            title="Toggle crosshair"
            aria-pressed={crosshair}
            onClick={toggleCrosshair}
          >
            <svg className="tool-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M12 3v5M12 16v5M3 12h5M16 12h5" />
              <circle cx="12" cy="12" r="3" />
            </svg>
          </button>
          <button
            className="control-btn icon-btn"
            aria-label="Toggle guide lines (G)"
            title="Toggle guide lines"
            aria-pressed={showGuides}
            onClick={toggleGuides}
          >
            <svg className="tool-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M4 7h16M4 17h16M7 4v16M17 4v16" />
              <path d="M9 12h6M12 9v6" />
            </svg>
          </button>
          <button
            className="control-btn text-control guide-control"
            aria-label="Toggle guide orientation"
            title="Change guide orientation"
            onClick={() => setGuideToggle((t) => (t === 'horizontal' ? 'vertical' : 'horizontal'))}
          >
            Guide: {guideToggle.charAt(0).toUpperCase() + guideToggle.slice(1)}
          </button>
          <button
            className="control-btn icon-btn"
            aria-label="Toggle fullscreen (F)"
            title="Toggle fullscreen"
            onClick={toggleFullscreen}
          >
            <svg className="fullscreen-icon" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M8 3H3v5M16 3h5v5M8 21H3v-5M21 16v5h-5" />
            </svg>
          </button>
          <button className="control-btn" aria-label="Clear all guides" title="Clear all guide lines" onClick={clearAllGuides}>
            Clear Guides
          </button>
        </div>

        <button
          className="header-status"
          type="button"
          aria-label="Open screen calibration"
          title="Open screen calibration"
          onClick={() => setShowCalibration(true)}
        >
          <span className="status-dot" />
          <span>{statusText}</span>
          <span className="status-arrow" aria-hidden="true">
            ↗
          </span>
        </button>
      </header>

      <div className="canvas-label" aria-hidden="true">
        <span className="canvas-kicker">ACTUAL SIZE</span>
        <span>Place an object against any edge</span>
      </div>
      <div className="canvas-tools" aria-hidden="true">
        <span className="canvas-tool-dot" />
        <span>
          Guides {guides.length} · {calibration.dpi} PPI
        </span>
      </div>

      <div ref={crosshairRef} id="crosshair" className="crosshair" aria-hidden="true" style={{ display: 'none' }}>
        <div className="crosshair-h" />
        <div className="crosshair-v" />
      </div>
      <div ref={coordsRef} id="coords" className="coords" aria-live="polite" aria-atomic="true" style={{ display: 'none' }} />

      <div id="sr-announcer" aria-live="polite" aria-atomic="true" className="sr-only" />

      <footer className="app-footer">
        <span className="footer-brand">Real Ruler</span>
        <span className="footer-divider" aria-hidden="true" />
        <span>Measurements stay on this device</span>
        <nav aria-label="Footer links">
          <a href="/en/about">About</a>
          <a href="/en/privacy-policy">Privacy</a>
          <a href="/en/contact">Contact</a>
        </nav>
      </footer>

      <CalibrationModal
        open={showCalibration}
        onClose={() => setShowCalibration(false)}
        current={calibration}
        onChange={handleCalibrationChange}
      />
    </div>
  );
}
